# Generated by Django 5.1.4 on 2025-03-13 20:53

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=500)),
                ('revision_number', models.IntegerField()),
                ('published_date', models.DateTimeField()),
                ('publisher', models.CharField(max_length=1000)),
                ('author', models.TextField()),
                ('added_date', models.DateTimeField(default=datetime.date.today)),
                ('genre', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
