# Generated by Django 5.1.4 on 2025-03-14 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='images/books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
