# Generated by Django 5.1.4 on 2025-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_checked_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='expected_return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
