# Generated by Django 5.1.4 on 2025-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_date_checked_out_book_expected_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expected_return_date',
            field=models.DateField(null=True),
        ),
    ]
